### ISSUE TITLE
libjpeg is Broken

### ISSUE THREAD

**Issue by andressbarajas** [KallistiOS/kos-ports#20]
It's broken and has been for many (~15!!!!) years.  Maybe even going back to version 6b.  There is only one example in KOS that uses this library (Parallax/raster_melt).  We need to find another library because according to the documentation it is still being worked on and the next release is sometime next year.  So while it is still being maintained it doesnt work for us.  @ljsebald has suggested replacing it with this: https://github.com/libjpeg-turbo/libjpeg-turbo

**Comment by gyrovorbis** [comment]
SWAT has just reported that it works fine for him in SDL_image. Useful information for a potential future sleuther:

```
BlueCrab — Today at 10:11 PM
then it's quite possibly something that changed in the api between 6b and now that we didn't account for?
```

**Comment by andressbarajas** [comment]
Here is the repo for SDL: https://sourceforge.net/p/cadcdev/sdl/ci/master/tree/base/src/

I cant find SDL_image anywhere in this port

**Comment by darcagn** [comment]
Looked into this for a sec, old kos-ports in kos 2.0 used to have 6b and then when the new kos-ports was created it started with 9a. There were major API changes in 7 and 8, so that's probably where the issues came from.

As mentioned above, libjpeg-turbo sounds like it would be a suitable replacement, as it specifically has API compatibility with libjpeg 6b (and it's faster to boot). Unfortunately it uses a more complicated CMake build system and I'm not even sure where to begin to include it as a kos-port.

**Comment by darcagn** [comment]
This one was taken care of by #39 . Thanks @andressbarajas !
